# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c384381555d9c4fc4ebafb0fb6034896b8bb0e621e95f5e6c07b572b37a953e24a62138ad9724a409b3563a1b6db39fe6e32c9986e4bfb30ae6156a83e571ce4

test:
  secret_key_base: 521b6f5286fce1807632e31b33ad2179b49b022cb3eb4daed3bda8954482786ea157d5909a850f265c7c0bf92e65fb0d45532dcc871fb8de287b75ec732406b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
